version: 2
jobs:
  build:
    docker:
      - image: gcc:7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: gcc version
          command: gcc --version

      - run:
          name: g++ version
          command: g++ --version

      - run:
          name: g++ version
          command: g++ --version

      - run:
          name: Build C
          command: gcc main.c -o C

      - run:
          name: Build C++
          command: g++ main.cpp -o C++

      - run:
          name: Test C
          command: ./C

      - run:
          name: Test C++
          command: ./C++
