version: 2
jobs:
  build:
    docker:
      - image: starlabio/arm-linux-gnueabihf

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: gcc version
          command: gcc --version

      - run:
          name: g++ version
          command: g++ --version

      - run:
          name: cmake version
          command: cmake --version

      - run:
          name: Run CMake
          command: mkdir build && cd build && cmake ..

      - run:
          name: Build
          command: cd build && make && file C

      - run:
          name: Test C
          command: build/C