version: 2
jobs:
  build:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Build
          command: gcc main.c
      - run:
          name: Run
          command: ./a.out
