version: 2
jobs:
  build:
    docker:
      - image: purplekarrot/arm-linux-gnueabihf

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y file

      - run:
          name: gcc version
          command: arm-linux-gnueabihf-gcc --version

      - run:
          name: g++ version
          command: arm-linux-gnueabihf-g++ --version

      - run:
          name: cmake version
          command: cmake --version

      - run:
          name: Run CMake
          command: mkdir build && cd build && cmake ..

      - run:
          name: Build
          command: cd build && make && file C