version: 2
jobs:
  build:
    docker:
      - image: rabits/qt:5.9-desktop
    steps:
      - checkout
      - run:
        name: qmake
        command: echo "Run qmake here"
  test:
    docker:
      - image: rabits/qt:5.9-desktop
    steps:
      - checkout
      - run:
        name: Begin Test
        command: date
      - run:
        name: End Test
        command: date
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
        filters:
          branches:
            only: master
