version: 2
jobs:
  build:
    docker:
      - image: rabits/qt:5.9-desktop

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: echo

      - run:
          name: build
          command: echo

      - run:
          name: test
          command: echo