version: 2
jobs:
  build:
    docker:
      - image: purplekarrot/arm-linux-gnueabihf
      # - image: rikorose/gcc-cmake:latest

    working_directory: ~/repo

    environment:
      CC: arm-linux-gnueabihf-gcc
      CXX: arm-linux-gnueabihf-g++

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y file

      - run:
          name: gcc version
          command: ${CC} --version

      - run:
          name: g++ version
          command: ${CXX} --version

      - run:
          name: Run CMake
          command: cmake --version
          command: mkdir build && cd build && cmake .. && make help

      - run:
          name: Build C
          command: cd build && make C.elf && file C.elf && cd ~/repo
          command: cd build && make C++.elf && file C++.elf  && cd ~/repo

      - store_artifacts:
          path: build/*.elf
