version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y subversion g++ zlib1g-dev build-essential git python rsync man-db libncurses5-dev gawk gettext unzip file libssl-dev wget zip time
      - run:
          name: Checkout Files
          command: git clone https://git.openwrt.org/openwrt/openwrt.git/ && cd openwrt && git checkout v18.06.1
      - run:
          name: Update script
          command: cd openwrt && ./scripts/feeds update -a
      - run:
          name: Install script
          command: cd openwrt && ./scripts/feeds install -a
      - run:
          name: Make Configuration
          command: cp diffconfig openwrt/.config && cd openwrt && make defconfig
      - run:
          name: Make Download
          command: cd openwrt && make -j"$(nproc)" download
      - run:
          name: Build
          command: cd openwrt && make -j"$(nproc)"
