version: 2
jobs:
  build:
    docker:
      - image: rabits/qt:5.9-desktop
    steps:
      - checkout
      - run:
          name: List of Images
          command: docker images
      - run:
          name: Build
          command: gcc main.c
      - run:
          name: Run
          command: ./a.out
