version: 2
jobs:
  build:
    docker:
      - image: rabits/qt:5.11-desktop

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: echo

      - run:
          name: build
          command: |
              qmake TestingCircleCI.pro
              make
              ls -lah
              
      - run:
          name: view depa
          command: ldd libqxcb.so

      - run:
          name: test
          command: ./TestingCircleCI
      - run:
          name: test
          command: make check
